source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/screen.conf
source = ~/.config/hypr/exec.conf

# env = GDK_BACKEND,x11

xwayland {
  force_zero_scaling = true
  use_nearest_neighbor = true
  enabled = true
}

misc:vfr = true
