general { 
  ignore_empty_input = true
  fail_timeout = 500
  hide_cursor = true
}

# BACKGROUND
background {
  path = screenshot
  blur_passes = 2
  blur_size = 2
  noise = 0.03
}

label {
    monitor =
    text =  $USER
    color = rgba(a89984ff)
    font_size = 20 
    font_family = FiraCode Nerd Font Mono

    position = 0, 350
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
  size = 500, 60
  outline_thickness = 0

  position = 0, 300
  halign = center
  valign = center

  placeholder_text = 

  dots_text_format = 
  dots_spacing = 0.1
  dots_size = 0.5

  fade_on_empty = false
  font_family = FiraCode Nerd Font Mono
  font_color = rgba(a89984ff)

  capslock_color = rgba(d79921ff)

  outer_color = rgba(0, 0, 0, 0.0)
  inner_color = rgba(0, 0, 0, 0.0)
  check_color = rgba(0, 0, 0, 0.0)

  fail_color = rgba(0, 0, 0, 0.0)
  fail_text = <i>$FAIL ($ATTEMPTS)</i>
}
