general {
  # gaps_out = 10, 10, 10, 10
  # gaps_in = 5

  gaps_out = 0
  gaps_in = 0

  # Borders
  border_size = 2
  col.active_border = rgba(7c6f64ff)
  col.inactive_border = rgba(3c3836ff)

  layout = dwindle
}

dwindle {
  preserve_split = true
}

decoration {
  # rounding = 5

  blur {
    enabled = true
	  special = true
    new_optimizations = true
    size = 4
    passes = 3
    contrast = 1
    vibrancy = 1
    noise = 0.03
  }

  # Shadow
  # drop_shadow = false
  # shadow_offset = 6 6
  # shadow_range = 6
  # shadow_render_power = 0
  # col.shadow = 0x66000000
  # shadow_ignore_window = false

  # screen_shader = ./shader.glsl
}

animations {
  enabled = true

  # bezier = anim, 0.5, 0.25, 0.25, 1 
  bezier = custom_bezier, 0.5, 0, 0.25, 1 

  animation = windows,     	true,   6,	custom_bezier, popin 10%
  animation = windowsOut,   true,   6,  custom_bezier, popin 90%
  animation = layers,      	true,   6,	custom_bezier, popin 10% 
  animation = fade,        	true,	  3,	custom_bezier
  # animation = fadeOut,      false                                 # for scratchpasd
  animation = border,      	true,   3,	custom_bezier
  animation = borderangle, 	false
  animation = workspaces,  	true,	  3,	custom_bezier, slidevert
  animation = zoomFactor,  	true,	  6,	custom_bezier
  animation = monitorAdded,	true,	  6,	custom_bezier
}
